import React from 'react'
import { Col, Container, Row } from 'react-bootstrap'
import Button from 'react-bootstrap/Button';
import Card from 'react-bootstrap/Card';
import { Link } from 'react-router-dom';


function Landing() {
  return (
    <div>
      <Container>
        <Row className='mt-5'>
          <Col lg={6}>
            <div className='mt-5'>
              <h1>Video Uploader</h1>
              <p className='fs-4 mt-4'>Most definitions of music include a reference to sound and a list of universals of music can be generated by stating the elements (or aspects) of sound: pitch, timbre, loudness, duration, spatial location and texture.</p>
            <Link to={'/home'}>
            <button id='b1' className='btn ms-3'>get started</button>
            </Link>
           
            </div>

          </Col>

          <Col>
            <img className='w-80' style={{ height: '300px' }} src="https://i.postimg.cc/RVK6fnVy/original-4703d0ba72b72f87fa49a618a24a1f6d.gif" alt="" />

          </Col>
        </Row>

        <hr />

        <Row className='mt-5 mb-5 py-5'>
          <h1 className='mb-5 text-center'>Features</h1>
          <Col className='p-4'>

            <Card style={{ width: '18rem' }}>
              <Card.Img style={{ height: '300px' }} variant="top" src="https://i.postimg.cc/VLk6WjbH/2e9c6878eae5bbcdaa2d07ed4dbd79b8.gif" />
              <Card.Body>
                <Card.Title><b>managing video</b></Card.Title>
                <Card.Text>
                music endeavors to give an accurate and concise explanation of music's basic attributes or essential nature and it involves a process of defining what is meant by the term music.

                </Card.Text>
                
              </Card.Body>
            </Card>
          </Col>

          <Col className='p-4'>
            <Card style={{ width: '18rem' }}>
              <Card.Img style={{ height: '300px' }} variant="top" src="https://i.postimg.cc/hPQFnvFt/How-to-Use-Spotify-Canvas-for-Cool-Video-Features-header.gif" />
              <Card.Body>
                <Card.Title><b>categorise videos</b></Card.Title>
                <Card.Text>
                The audience hears only whatever ambient sounds may occur in the room.music's basic attributes or essential nature and it involves a  Some argue that 4′33″ is not music because, among other reasons
                </Card.Text>
                
              </Card.Body>
            </Card>
          </Col>

          <Col className='p-4'>
            <Card style={{ width: '18rem' }}>
              <Card.Img style={{ height: '300px' }} variant="top" src="https://i.postimg.cc/ZnTrcCrF/af06d588955337-5de67afb72d40.gif" />
              <Card.Body>
                <Card.Title><b>Watch histroy</b></Card.Title>
                <Card.Text>
                Because of differing fundamental concepts of music, the languages of many cultures do not contain a word that can be accurately translated as "music" as that word is generally understood cultures

                </Card.Text>
               
              </Card.Body>
            </Card>
          </Col>

        </Row>
      </Container>

    </div>
  )
}

export default Landing